// Bild-Illustrationen, Themen-Bilder und bildbasierte Fragen/Karten (von Hand kuratiert).
window.BAUKO_MEDIA = {
  // Titelbild pro Thema (Startbildschirm)
  topicImages: {
    "Einwirkungen – Grundlagen": "img/lastarten.svg",
    "Einwirkungen – Schnee, Wind, Lastkombination": "img/lastarten.svg",
    "Holzbau & Brettsperrholz (CLT)": "img/clt-aufbau.svg",
    "Flachdachkonstruktionen": "img/warmdach-kaltdach.svg",
    "Fenster & Fassaden": "img/glasfassade.jpg",
    "Verbundträger & Tragwerk": "img/verbundtraeger.svg"
  },

  quiz: [
    { topic: "Holzbau & Brettsperrholz (CLT)", image: "img/clt-aufbau.svg",
      q: "Welcher Holzwerkstoff ist im Bild dargestellt (mehrere kreuzweise verleimte Brettlagen)?",
      options: ["Brettschichtholz (BSH)", "Brettsperrholz (CLT)", "Furnierschichtholz (LVL)", "Dreischichtplatte"],
      answer: 1, explanation: "Kreuzweise (um 90° versetzte) flächig verleimte Brettlagen kennzeichnen Brettsperrholz/CLT." },
    { topic: "Holzbau & Brettsperrholz (CLT)", image: "img/clt-aufbau.svg",
      q: "Warum kann Brettsperrholz Lasten in beide Richtungen abtragen?",
      options: ["Weil alle Lagen in gleicher Richtung liegen", "Weil die Lagen um 90° gekreuzt verleimt sind", "Weil es aus Metall besteht", "Weil es hohl ist"],
      answer: 1, explanation: "Die gekreuzte Anordnung der Lagen erzeugt Tragfähigkeit in beide Richtungen und eine gute Scheibenwirkung." },
    { topic: "Einwirkungen – Grundlagen", image: "img/lastarten.svg",
      q: "Welche Lastart zeigt die oberste Skizze (ein einzelner Kraftpfeil)?",
      options: ["Gleichstreckenlast", "Dreieckslast", "Einzellast", "Flächenlast"],
      answer: 2, explanation: "Ein einzelner konzentrierter Kraftpfeil steht für eine Einzel-/Punktlast F [kN]." },
    { topic: "Einwirkungen – Grundlagen", image: "img/lastarten.svg",
      q: "Wie heißt eine gleichmäßig über die Länge verteilte Last (mittlere Skizze)?",
      options: ["Einzellast", "Gleichstreckenlast", "Dreieckslast", "Momentenlast"],
      answer: 1, explanation: "Eine über die Länge konstante Linienlast heißt Gleichstreckenlast q [kN/m]." },
    { topic: "Fenster & Fassaden", image: "img/pfosten-riegel.svg",
      q: "Welche Fassadenkonstruktion ist schematisch dargestellt?",
      options: ["Elementfassade", "Vorhangfassade aus Beton", "Pfosten-Riegel-Fassade", "Massivwand"],
      answer: 2, explanation: "Das Raster aus vertikalen Pfosten und horizontalen Riegeln mit Glasfüllung ist die Pfosten-Riegel-Fassade." },
    { topic: "Fenster & Fassaden", image: "img/pfosten-riegel.svg",
      q: "Welche Bauteile übernehmen bei der Pfosten-Riegel-Fassade primär die vertikale Lastabtragung?",
      options: ["Die Riegel", "Die Pfosten", "Die Glasscheiben", "Die Dichtungen"],
      answer: 1, explanation: "Die vertikalen Pfosten sind die tragenden Hauptprofile; die Riegel spannen horizontal dazwischen." },
    { topic: "Verbundträger & Tragwerk", image: "img/verbundtraeger.svg",
      q: "Welche Aufgabe haben die rot dargestellten Kopfbolzen?",
      options: ["Sie dämmen den Träger", "Sie übertragen die Schubkraft zwischen Stahl und Beton", "Sie tragen die gesamte Biegelast allein", "Sie dienen nur der Optik"],
      answer: 1, explanation: "Kopfbolzendübel stellen den Schubverbund her – sie übertragen die Schubkräfte zwischen Betonplatte und Stahlprofil." },
    { topic: "Verbundträger & Tragwerk", image: "img/verbundtraeger.svg",
      q: "Was ist im Bild dargestellt?",
      options: ["Ein reiner Stahlträger", "Eine Stahlbetonstütze", "Ein Stahl-Beton-Verbundträger", "Ein Holzbalken"],
      answer: 2, explanation: "Betonplatte oben, Stahlprofil unten, verbunden durch Kopfbolzen = Stahl-Beton-Verbundträger." },
    { topic: "Flachdachkonstruktionen", image: "img/warmdach-kaltdach.svg",
      q: "Worin unterscheidet sich das Kaltdach vom Warmdach?",
      options: ["Es hat keine Wärmedämmung", "Es besitzt eine belüftete Luftschicht", "Es hat keine Abdichtung", "Es ist immer begrünt"],
      answer: 1, explanation: "Das Kaltdach ist belüftet – zwischen Dämmung und Dachhaut liegt eine durchströmte Luftschicht; das Warmdach ist nicht belüftet." },
    { topic: "Holzbau & Brettsperrholz (CLT)", image: "img/fachwerk.jpg",
      q: "Welche Holzbauweise zeigt das Foto (sichtbares Holzskelett mit ausgefüllten Gefachen)?",
      options: ["Blockbau", "Fachwerkbau", "Holztafelbau", "Brettsperrholzbau"],
      answer: 1, explanation: "Das sichtbare Stabwerk aus Ständern, Riegeln und Streben mit ausgefüllten Gefachen ist typischer Fachwerkbau." },
    { topic: "Holzbau & Brettsperrholz (CLT)", image: "img/blockbau.jpg",
      q: "Welche Bauweise kennzeichnet dieses Gebäude aus waagerecht liegenden Vollholzbalken?",
      options: ["Skelettbau", "Blockbau", "Holzrahmenbau", "Holztafelbau"],
      answer: 1, explanation: "Übereinander liegende, massive Vollholzbalken bilden die Wand – das ist der Blockbau." },
    { topic: "Holzbau & Brettsperrholz (CLT)", image: "img/skelettbau.jpg",
      q: "Welches Tragsystem zeigt dieser Rohbau aus Stützen und Trägern?",
      options: ["Massivbau", "Skelettbau", "Blockbau", "Schalenbau"],
      answer: 1, explanation: "Stabförmige Stützen und Träger bilden das Traggerüst – Skelettbau; die Aussteifung erfolgt durch zusätzliche Bauteile." }
  ],

  flashcards: [
    { topic: "Holzbau & Brettsperrholz (CLT)", image: "img/clt-aufbau.svg",
      front: "Aufbau von Brettsperrholz (CLT)?",
      back: "Mehrere Brettlagen werden kreuzweise (um 90° versetzt) flächig verleimt. Folge: trägt in beide Richtungen, gute Scheibenwirkung, formstabil." },
    { topic: "Einwirkungen – Grundlagen", image: "img/lastarten.svg",
      front: "Die drei dargestellten Lastarten?",
      back: "Einzellast F [kN] (konzentriert), Gleichstreckenlast q [kN/m] (gleichmäßig verteilt), Dreieckslast (linear veränderlich)." },
    { topic: "Fenster & Fassaden", image: "img/pfosten-riegel.svg",
      front: "Pfosten-Riegel-Fassade – Prinzip?",
      back: "Rasterkonstruktion aus vertikalen, tragenden Pfosten und horizontalen Riegeln; die Felder werden mit Glas (oder Paneelen) gefüllt." },
    { topic: "Verbundträger & Tragwerk", image: "img/verbundtraeger.svg",
      front: "Verbundträger – Prinzip?",
      back: "Betonplatte und Stahlprofil wirken gemeinsam. Kopfbolzendübel stellen den Schubverbund her, sodass beide Querschnittsteile zusammen tragen." },
    { topic: "Flachdachkonstruktionen", image: "img/warmdach-kaltdach.svg",
      front: "Warmdach vs. Kaltdach?",
      back: "Warmdach: nicht belüftet, Schichten liegen direkt aufeinander. Kaltdach: belüftet, mit durchströmter Luftschicht zwischen Dämmung und Dachhaut." },
    { topic: "Holzbau & Brettsperrholz (CLT)", image: "img/fachwerk.jpg",
      front: "Fachwerkbau erkennen?",
      back: "Sichtbares Holzskelett aus Ständern, Riegeln und Streben; die Gefache dazwischen sind ausgefüllt. Zählt zu den Wandbauweisen." },
    { topic: "Holzbau & Brettsperrholz (CLT)", image: "img/blockbau.jpg",
      front: "Blockbau erkennen?",
      back: "Massive, waagerecht übereinander liegende Vollholzbalken bilden die tragende Wand. Traditionelle Massivholz-Wandbauweise." },
    { topic: "Holzbau & Brettsperrholz (CLT)", image: "img/skelettbau.jpg",
      front: "Skelettbau erkennen?",
      back: "Stabförmige Einzelbauteile (Stützen vertikal, Träger horizontal) tragen die Lasten; Raumabschluss und Aussteifung durch nachgeordnete Bauteile." }
  ]
};
